<?php declare(strict_types=1);

return [
    0 =>
        array (
            'id' => 1,
            'parent_id' => NULL,
            'name' => 'First category',
            'name_on_site' => NULL,
            'slug' => 'First-category',
            'url' => '/First-category',
            'meta_title' => 'First category title',
            'meta_description' => 'First category description',
            'description' => 'First category content',
            'created_at' => 1392559490,
            'updated_at' => 1392559490,
        ),
    1 =>
        array (
            'id' => 2,
            'parent_id' => NULL,
            'name' => 'Second category',
            'name_on_site' => NULL,
            'slug' => 'Second-category',
            'url' => '/Second-category',
            'meta_title' => 'Second category title',
            'meta_description' => 'Second category description',
            'description' => 'Second category content',
            'created_at' => 1392559490,
            'updated_at' => 1392559490,
        ),
    2 =>
        array (
            'id' => 3,
            'parent_id' => NULL,
            'name' => 'Third category',
            'name_on_site' => NULL,
            'slug' => 'Third-category',
            'url' => '/Third-category',
            'meta_title' => 'Third category title',
            'meta_description' => 'Third category description',
            'description' => 'Third category content',
            'created_at' => 1392559490,
            'updated_at' => 1392559490,
        ),
    3 =>
        array (
            'id' => 4,
            'parent_id' => 1,
            'name' => 'Second level',
            'name_on_site' => NULL,
            'slug' => 'second-level',
            'url' => '/first-category/second-level',
            'meta_title' => NULL,
            'meta_description' => NULL,
            'description' => NULL,
            'created_at' => 1571145253,
            'updated_at' => 1571145253,
        ),
    4 =>
        array (
            'id' => 5,
            'parent_id' => 4,
            'name' => 'Third level',
            'name_on_site' => NULL,
            'slug' => 'third-level',
            'url' => '/first-category/second-level/third-level',
            'meta_title' => NULL,
            'meta_description' => NULL,
            'description' => NULL,
            'created_at' => 1571145253,
            'updated_at' => 1571145253,
        ),
    5 =>
        array (
            'id' => 6,
            'parent_id' => 5,
            'name' => 'Fourth level',
            'name_on_site' => NULL,
            'slug' => 'fourth-level',
            'url' => '/first-category/second-level/third-level/fourth-level',
            'meta_title' => NULL,
            'meta_description' => NULL,
            'description' => NULL,
            'created_at' => 1571145253,
            'updated_at' => 1571145253,
        ),
    6 =>
        array (
            'id' => 7,
            'parent_id' => 6,
            'name' => 'Fifth level',
            'name_on_site' => NULL,
            'slug' => 'fifth-level',
            'url' => '/first-category/second-level/third-level/fourth-level/fifth-level',
            'meta_title' => NULL,
            'meta_description' => NULL,
            'description' => NULL,
            'created_at' => 1571145254,
            'updated_at' => 1571145254,
        ),
    7 =>
        array (
            'id' => 8,
            'parent_id' => 7,
            'name' => 'Sixth level',
            'name_on_site' => NULL,
            'slug' => 'sixth-level',
            'url' => '/first-category/second-level/third-level/fourth-level/fifth-level/sixth-level',
            'meta_title' => NULL,
            'meta_description' => NULL,
            'description' => NULL,
            'created_at' => 1571145254,
            'updated_at' => 1571145254,
        ),
    8 =>
        array (
            'id' => 9,
            'parent_id' => 8,
            'name' => 'Seventh level',
            'name_on_site' => NULL,
            'slug' => 'seventh-level',
            'url' => '/first-category/second-level/third-level/fourth-level/fifth-level/sixth-level/seventh-level',
            'meta_title' => NULL,
            'meta_description' => NULL,
            'description' => NULL,
            'created_at' => 1571145254,
            'updated_at' => 1571145254,
        ),
    9 =>
        array (
            'id' => 10,
            'parent_id' => 9,
            'name' => 'Eighth level',
            'name_on_site' => NULL,
            'slug' => 'eighth-level',
            'url' => '/first-category/second-level/third-level/fourth-level/fifth-level/sixth-level/seventh-level/eighth-level',
            'meta_title' => NULL,
            'meta_description' => NULL,
            'description' => NULL,
            'created_at' => 1571145254,
            'updated_at' => 1571145254,
        ),
    10 =>
        array (
            'id' => 11,
            'parent_id' => 10,
            'name' => 'Ninth level',
            'name_on_site' => NULL,
            'slug' => 'ninth-level',
            'url' => '/first-category/second-level/third-level/fourth-level/fifth-level/sixth-level/seventh-level/eighth-level/ninth-level',
            'meta_title' => NULL,
            'meta_description' => NULL,
            'description' => NULL,
            'created_at' => 1571145255,
            'updated_at' => 1571145255,
        ),
    11 =>
        array (
            'id' => 12,
            'parent_id' => 11,
            'name' => 'Tenth level',
            'name_on_site' => NULL,
            'slug' => 'tenth-level',
            'url' => '/first-category/second-level/third-level/fourth-level/fifth-level/sixth-level/seventh-level/eighth-level/ninth-level/tenth-level',
            'meta_title' => NULL,
            'meta_description' => NULL,
            'description' => NULL,
            'created_at' => 1571145255,
            'updated_at' => 1571145255,
        ),
];
